### ISSUE TITLE
Not currently Open Source

### ISSUE THREAD

**Issue by iainsmith** [wswebcreation/saucelabs-vusb-gui#5]
**Environment (please complete the following information):**
 - Client version: All
 - OS version: All

**Describe the bug**
The README, is currently misleading as it states:

> This project is an Open Source Virtual USB GUI for Sauce Labs Virtual USB

However the source code is not currently available. The generally accepted definition of Open Source can be found here: https://opensource.org/osd

which includes: 

> 2. Source Code
The program must include source code, and must allow distribution in source code as well as compiled form. Where some form of a product is not distributed with source code, there must be a well-publicized means of obtaining the source code for no more than a reasonable reproduction cost, preferably downloading via the Internet without charge. The source code must be the preferred form in which a programmer would modify the program. Deliberately obfuscated source code is not allowed. Intermediate forms such as the output of a preprocessor or translator are not allowed.

**Expected behavior**
Either the Source Code should be available, or the README, LICENSE should be updated/removed to provide accurate information.

**Comment by wswebcreation** [comment]
@iainsmith 

You're totally right. This will change in a few weeks time, see https://github.com/wswebcreation/saucelabs-vusb-gui#why-is-the-source-code-not-provided
Version `1.0.0` is almost ready

**Comment by wswebcreation** [comment]
@iainsmith 

I've moved the repo to https://github.com/saucelabs/saucelabs-vusb-app and the code is now open source. It now also uses the Sauce Labs Real Device Cloud instead of the Legacy one (TestObject).

This project is now deprecated and version [0.5.0](https://github.com/wswebcreation/saucelabs-vusb-gui/releases/tag/0.5.0) is the last supported version that works with the Legacy RDC
